name: sample_finserv_demo

on:
 # pull_request:  
 push:
  branches: [ master ]       
 
jobs:
  build:
   
     runs-on: macOS-latest

     steps:
            - name: checkout
              uses: actions/checkout@master
              
            - name: Build Archive
              run:  xcodebuild clean archive -project Fiserv_Demo.xcodeproj -scheme Fiserv_Demo -sdk iphoneos -configuration Debug  PROVISIONING_STYLE="Automatic"                  
    
