name: sample_finserv_demo

on:
 # pull_request:  
 push:
  branches: [ master ]       
 
jobs:
  build:
   
     runs-on: macOS-latest

     steps:
            - name: checkout
              uses: actions/checkout@master
              
            - name: Clean Project
              run:  xcodebuild clean -project Fiserv_Demo.xcodeproj -scheme Fiserv_Demo
              
            - name: Executing code
              run:  xcodebuild -project Fiserv_Demo.xcodeproj -scheme Fiserv_Demo 
              
            - name: Build Archive
              run:  xcodebuild clean archive -project Fiserv_Demo.xcodeproj -scheme Fiserv_Demo -configuration Debug -archivePath $PWD/build/Fiserv_Demo.xcarchive PROVISIONING_STYLE="Automatic"                   
    
